<?php

namespace AppBundle\Entity;

/**
 * TauntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TauntRepository extends \Doctrine\ORM\EntityRepository
{
		public function findLasts() {

		return $queryBuilder = $this->createQueryBuilder('i')
		->where('i.published = true')
		->orderBy("i.createdAt","DESC")
		->getQuery()
		->getResult();
	}

			public function findUnpublished() {

		return $queryBuilder = $this->createQueryBuilder('i')
		->where('i.published = false')
		->orderBy("i.createdAt","DESC")
		->getQuery()
		->getResult();
	}
}
