<?php

namespace AppBundle\Entity;

/**
 * TauntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TauntRepository extends \Doctrine\ORM\EntityRepository
{
}
